# Generated by Django 3.2.7 on 2021-10-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
