# Generated by Django 3.2.7 on 2021-09-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that username already exists.'}, max_length=60, unique=True, verbose_name='email')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=80)),
                ('dob', models.DateField(max_length=8)),
                ('company_name', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
